version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - sqlite-data:/workspace/data
    command: sleep infinity
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Data Source=/workspace/data/app.db;Cache=Shared"
    ports:
      - "5000:5000"
      - "5001:5001"

volumes:
  sqlite-data:
    driver: local
